#!/usr/bin/python3
import os

aliasFiles = ["/etc/avahi/aliases"] + [ os.path.join("/etc/avahi/aliases.d/", f) for f in os.listdir("/etc/avahi/aliases.d/") ]

for file in aliasFiles:
    with open(file, "r") as f:
        print("{} :".format(file))
        for line in f:
            if not line.startswith("#"):
                print("    {}".format(line.rstrip("\n")))
