#!/usr/bin/python3
import os, sys

if os.geteuid() != 0:
    exit("You need to have root privileges to run this script.\nPlease try again using 'sudo'.")

if len(sys.argv) < 2:
    exit("Usage: avahi-remove-alias alias_1.local [alias_2.local] [alias_3.local]...")

toRemove = sys.argv[1:]

aliasFiles = ["/etc/avahi/aliases"] + [ os.path.join("/etc/avahi/aliases.d/", f) for f in os.listdir("/etc/avahi/aliases.d/") ]

for file in aliasFiles:
    remainingLines = [line for line in open(file, "r") if line.rstrip("\n") not in toRemove]
    if file.startswith("/etc/avahi/aliases.d/") and len(remainingLines) == 0:
        os.remove(file)
    else:
        with open(file, "w") as f:
            f.writelines(remainingLines)

os.system("systemctl restart avahi-aliases.service")
print("done")
