#!/usr/bin/python3
import dbus

class avahi:
    DBUS_NAME = "org.freedesktop.Avahi"
    DBUS_PATH_SERVER = "/"
    DBUS_INTERFACE_SERVER = "org.freedesktop.Avahi.Server"
    DBUS_INTERFACE_ENTRY_GROUP = "org.freedesktop.Avahi.EntryGroup"
    IF_UNSPEC = -1
    PROTO_UNSPEC = -1

CLASS_IN = 0x01
TYPE_CNAME = 0x05

TTL = 60

def publish_cname(cname):
    bus = dbus.SystemBus()
    server = dbus.Interface(bus.get_object(avahi.DBUS_NAME, avahi.DBUS_PATH_SERVER),
            avahi.DBUS_INTERFACE_SERVER)
    group = dbus.Interface(bus.get_object(avahi.DBUS_NAME, server.EntryGroupNew()),
            avahi.DBUS_INTERFACE_ENTRY_GROUP)

    cname = encode_dns(cname)
    target = createRR(server.GetHostNameFqdn())

    group.AddRecord(avahi.IF_UNSPEC, avahi.PROTO_UNSPEC, dbus.UInt32(0), cname, CLASS_IN, TYPE_CNAME, TTL, target)
    group.Commit()


def encode_dns(name):
    out = []
    for part in name.split("."):
        if len(part) == 0: continue
        out.append(part)
    return ".".join(out).encode("ASCII")

def createRR(name):
    out = []
    for part in name.split("."):
        if len(part) == 0: continue
        out.append(chr(len(part)))
        out.append(part)
    out.append("\0")
    return "".join(out).encode("ASCII")

if __name__ == "__main__":
    import time, os
    aliasFiles = ["/etc/avahi/aliases"] + [ os.path.join("/etc/avahi/aliases.d/", f) for f in os.listdir("/etc/avahi/aliases.d/") ]

    for file in aliasFiles:
        with open(file, "r") as f:
            for alias in [line.rstrip("\n") for line in f if not line.startswith("#")]:
                print("{}: Publishing".format(alias))
                if not alias.endswith(".local"):
                    print("{}: adding .local to unsupported address".format(alias))
                    alias = "{}.local".format(alias)
                publish_cname(alias)
    try:
        # Just loop forever
        while 1: time.sleep(60)
    except KeyboardInterrupt:
        print("Exiting")
